/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FundRouteImport } from './routes/fund'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIdRouteImport } from './routes/posts/$id'
import { Route as PersonIdRouteImport } from './routes/person/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTreeRouteImport } from './routes/admin/tree'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminPersonsRouteImport } from './routes/admin/persons'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminFundRouteImport } from './routes/admin/fund'
import { Route as ApiPostsIndexRouteImport } from './routes/api/posts/index'
import { Route as ApiPersonsIndexRouteImport } from './routes/api/persons/index'
import { Route as ApiNotificationsIndexRouteImport } from './routes/api/notifications/index'
import { Route as ApiMediaIndexRouteImport } from './routes/api/media/index'
import { Route as ApiFundIndexRouteImport } from './routes/api/fund/index'
import { Route as ApiPostsIdRouteImport } from './routes/api/posts/$id'
import { Route as ApiPersonsTreeRouteImport } from './routes/api/persons/tree'
import { Route as ApiPersonsMarriagesRouteImport } from './routes/api/persons/marriages'
import { Route as ApiPersonsIdRouteImport } from './routes/api/persons/$id'
import { Route as ApiMemoriesPersonIdRouteImport } from './routes/api/memories/$personId'
import { Route as ApiMediaIdRouteImport } from './routes/api/media/$id'
import { Route as ApiHomepageDataRouteImport } from './routes/api/homepage/data'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FundRoute = FundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PostsRoute,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTreeRoute = AdminTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPersonsRoute = AdminPersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFundRoute = AdminFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPostsIndexRoute = ApiPostsIndexRouteImport.update({
  id: '/api/posts/',
  path: '/api/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPersonsIndexRoute = ApiPersonsIndexRouteImport.update({
  id: '/api/persons/',
  path: '/api/persons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsIndexRoute = ApiNotificationsIndexRouteImport.update({
  id: '/api/notifications/',
  path: '/api/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIndexRoute = ApiMediaIndexRouteImport.update({
  id: '/api/media/',
  path: '/api/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFundIndexRoute = ApiFundIndexRouteImport.update({
  id: '/api/fund/',
  path: '/api/fund/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIdRoute = ApiPostsIdRouteImport.update({
  id: '/api/posts/$id',
  path: '/api/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPersonsTreeRoute = ApiPersonsTreeRouteImport.update({
  id: '/api/persons/tree',
  path: '/api/persons/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPersonsMarriagesRoute = ApiPersonsMarriagesRouteImport.update({
  id: '/api/persons/marriages',
  path: '/api/persons/marriages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPersonsIdRoute = ApiPersonsIdRouteImport.update({
  id: '/api/persons/$id',
  path: '/api/persons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoriesPersonIdRoute = ApiMemoriesPersonIdRouteImport.update({
  id: '/api/memories/$personId',
  path: '/api/memories/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomepageDataRoute = ApiHomepageDataRouteImport.update({
  id: '/api/homepage/data',
  path: '/api/homepage/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/fund': typeof FundRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/tree': typeof TreeRoute
  '/admin/fund': typeof AdminFundRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/persons': typeof AdminPersonsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/tree': typeof AdminTreeRoute
  '/admin/users': typeof AdminUsersRoute
  '/person/$id': typeof PersonIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/homepage/data': typeof ApiHomepageDataRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/memories/$personId': typeof ApiMemoriesPersonIdRoute
  '/api/persons/$id': typeof ApiPersonsIdRoute
  '/api/persons/marriages': typeof ApiPersonsMarriagesRoute
  '/api/persons/tree': typeof ApiPersonsTreeRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/fund/': typeof ApiFundIndexRoute
  '/api/media/': typeof ApiMediaIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/persons/': typeof ApiPersonsIndexRoute
  '/api/posts/': typeof ApiPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/fund': typeof FundRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/tree': typeof TreeRoute
  '/admin/fund': typeof AdminFundRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/persons': typeof AdminPersonsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/tree': typeof AdminTreeRoute
  '/admin/users': typeof AdminUsersRoute
  '/person/$id': typeof PersonIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/homepage/data': typeof ApiHomepageDataRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/memories/$personId': typeof ApiMemoriesPersonIdRoute
  '/api/persons/$id': typeof ApiPersonsIdRoute
  '/api/persons/marriages': typeof ApiPersonsMarriagesRoute
  '/api/persons/tree': typeof ApiPersonsTreeRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/fund': typeof ApiFundIndexRoute
  '/api/media': typeof ApiMediaIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/persons': typeof ApiPersonsIndexRoute
  '/api/posts': typeof ApiPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/fund': typeof FundRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/tree': typeof TreeRoute
  '/admin/fund': typeof AdminFundRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/persons': typeof AdminPersonsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/tree': typeof AdminTreeRoute
  '/admin/users': typeof AdminUsersRoute
  '/person/$id': typeof PersonIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/homepage/data': typeof ApiHomepageDataRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/memories/$personId': typeof ApiMemoriesPersonIdRoute
  '/api/persons/$id': typeof ApiPersonsIdRoute
  '/api/persons/marriages': typeof ApiPersonsMarriagesRoute
  '/api/persons/tree': typeof ApiPersonsTreeRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/fund/': typeof ApiFundIndexRoute
  '/api/media/': typeof ApiMediaIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/persons/': typeof ApiPersonsIndexRoute
  '/api/posts/': typeof ApiPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/fund'
    | '/login'
    | '/posts'
    | '/tree'
    | '/admin/fund'
    | '/admin/notifications'
    | '/admin/persons'
    | '/admin/posts'
    | '/admin/tree'
    | '/admin/users'
    | '/person/$id'
    | '/posts/$id'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/homepage/data'
    | '/api/media/$id'
    | '/api/memories/$personId'
    | '/api/persons/$id'
    | '/api/persons/marriages'
    | '/api/persons/tree'
    | '/api/posts/$id'
    | '/api/fund/'
    | '/api/media/'
    | '/api/notifications/'
    | '/api/persons/'
    | '/api/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/fund'
    | '/login'
    | '/posts'
    | '/tree'
    | '/admin/fund'
    | '/admin/notifications'
    | '/admin/persons'
    | '/admin/posts'
    | '/admin/tree'
    | '/admin/users'
    | '/person/$id'
    | '/posts/$id'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/homepage/data'
    | '/api/media/$id'
    | '/api/memories/$personId'
    | '/api/persons/$id'
    | '/api/persons/marriages'
    | '/api/persons/tree'
    | '/api/posts/$id'
    | '/api/fund'
    | '/api/media'
    | '/api/notifications'
    | '/api/persons'
    | '/api/posts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/fund'
    | '/login'
    | '/posts'
    | '/tree'
    | '/admin/fund'
    | '/admin/notifications'
    | '/admin/persons'
    | '/admin/posts'
    | '/admin/tree'
    | '/admin/users'
    | '/person/$id'
    | '/posts/$id'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/homepage/data'
    | '/api/media/$id'
    | '/api/memories/$personId'
    | '/api/persons/$id'
    | '/api/persons/marriages'
    | '/api/persons/tree'
    | '/api/posts/$id'
    | '/api/fund/'
    | '/api/media/'
    | '/api/notifications/'
    | '/api/persons/'
    | '/api/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FundRoute: typeof FundRoute
  LoginRoute: typeof LoginRoute
  PostsRoute: typeof PostsRouteWithChildren
  TreeRoute: typeof TreeRoute
  PersonIdRoute: typeof PersonIdRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiHomepageDataRoute: typeof ApiHomepageDataRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiMemoriesPersonIdRoute: typeof ApiMemoriesPersonIdRoute
  ApiPersonsIdRoute: typeof ApiPersonsIdRoute
  ApiPersonsMarriagesRoute: typeof ApiPersonsMarriagesRoute
  ApiPersonsTreeRoute: typeof ApiPersonsTreeRoute
  ApiPostsIdRoute: typeof ApiPostsIdRoute
  ApiFundIndexRoute: typeof ApiFundIndexRoute
  ApiMediaIndexRoute: typeof ApiMediaIndexRoute
  ApiNotificationsIndexRoute: typeof ApiNotificationsIndexRoute
  ApiPersonsIndexRoute: typeof ApiPersonsIndexRoute
  ApiPostsIndexRoute: typeof ApiPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund': {
      id: '/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof FundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tree': {
      id: '/admin/tree'
      path: '/tree'
      fullPath: '/admin/tree'
      preLoaderRoute: typeof AdminTreeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/persons': {
      id: '/admin/persons'
      path: '/persons'
      fullPath: '/admin/persons'
      preLoaderRoute: typeof AdminPersonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fund': {
      id: '/admin/fund'
      path: '/fund'
      fullPath: '/admin/fund'
      preLoaderRoute: typeof AdminFundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/posts/': {
      id: '/api/posts/'
      path: '/api/posts'
      fullPath: '/api/posts/'
      preLoaderRoute: typeof ApiPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/persons/': {
      id: '/api/persons/'
      path: '/api/persons'
      fullPath: '/api/persons/'
      preLoaderRoute: typeof ApiPersonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/': {
      id: '/api/notifications/'
      path: '/api/notifications'
      fullPath: '/api/notifications/'
      preLoaderRoute: typeof ApiNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/': {
      id: '/api/media/'
      path: '/api/media'
      fullPath: '/api/media/'
      preLoaderRoute: typeof ApiMediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fund/': {
      id: '/api/fund/'
      path: '/api/fund'
      fullPath: '/api/fund/'
      preLoaderRoute: typeof ApiFundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$id': {
      id: '/api/posts/$id'
      path: '/api/posts/$id'
      fullPath: '/api/posts/$id'
      preLoaderRoute: typeof ApiPostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/persons/tree': {
      id: '/api/persons/tree'
      path: '/api/persons/tree'
      fullPath: '/api/persons/tree'
      preLoaderRoute: typeof ApiPersonsTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/persons/marriages': {
      id: '/api/persons/marriages'
      path: '/api/persons/marriages'
      fullPath: '/api/persons/marriages'
      preLoaderRoute: typeof ApiPersonsMarriagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/persons/$id': {
      id: '/api/persons/$id'
      path: '/api/persons/$id'
      fullPath: '/api/persons/$id'
      preLoaderRoute: typeof ApiPersonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories/$personId': {
      id: '/api/memories/$personId'
      path: '/api/memories/$personId'
      fullPath: '/api/memories/$personId'
      preLoaderRoute: typeof ApiMemoriesPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homepage/data': {
      id: '/api/homepage/data'
      path: '/api/homepage/data'
      fullPath: '/api/homepage/data'
      preLoaderRoute: typeof ApiHomepageDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminFundRoute: typeof AdminFundRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPersonsRoute: typeof AdminPersonsRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminTreeRoute: typeof AdminTreeRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFundRoute: AdminFundRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPersonsRoute: AdminPersonsRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminTreeRoute: AdminTreeRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PostsRouteChildren {
  PostsIdRoute: typeof PostsIdRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsIdRoute: PostsIdRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FundRoute: FundRoute,
  LoginRoute: LoginRoute,
  PostsRoute: PostsRouteWithChildren,
  TreeRoute: TreeRoute,
  PersonIdRoute: PersonIdRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiHomepageDataRoute: ApiHomepageDataRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiMemoriesPersonIdRoute: ApiMemoriesPersonIdRoute,
  ApiPersonsIdRoute: ApiPersonsIdRoute,
  ApiPersonsMarriagesRoute: ApiPersonsMarriagesRoute,
  ApiPersonsTreeRoute: ApiPersonsTreeRoute,
  ApiPostsIdRoute: ApiPostsIdRoute,
  ApiFundIndexRoute: ApiFundIndexRoute,
  ApiMediaIndexRoute: ApiMediaIndexRoute,
  ApiNotificationsIndexRoute: ApiNotificationsIndexRoute,
  ApiPersonsIndexRoute: ApiPersonsIndexRoute,
  ApiPostsIndexRoute: ApiPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
